/**
 * GEN SCRIPT (dev-time tool, not committed): turns Overpass JSON dumps into
 * the curated Tempe venue seed module committed at server/src/data/tempe-venues.ts.
 *
 * Dedup guard: canonicalize name (lowercase, strip punctuation/brand suffixes)
 * + round coords to ~55m grid; drop entries whose grid cell is already taken
 * by a same-name entry (OSM often maps the same POI as node AND way).
 */
import { readFileSync, writeFileSync } from "node:fs";

interface El { type: string; id: number; lat?: number; lon?: number; center?: { lat: number; lon: number }; tags?: Record<string, string> }
interface OsmJson { elements: El[] }

type Cat = "bar" | "club" | "concert" | "restaurant" | "house" | "other";

function canonicalName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[’']/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/\b(the|a|an|inc|llc|ltd|co|company)\b/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

const LARGE = new Set([
  "ASU Gammage Auditorium", "Mountain America Stadium", "Desert Financial Club",
  "Mullett Arena", "Wells Fargo Arena", "Tempe Center for the Arts", "NIRVANA Food + Wine",
]);

function classify(t: Record<string, string>): Cat | null {
  const amen = t["amenity"] ?? "";
  const shop = t["shop"] ?? "";
  const leisure = t["leisure"] ?? "";
  const tourism = t["tourism"] ?? "";
  if (amen === "nightclub" || amen === "discotheque" || leisure === "nightclub" || leisure === "music_venue") return "club";
  if (amen === "bar" || amen === "pub" || amen === "biergarten" || shop === "hookah_lounge" || amen === "hookah_lounge") return "bar";
  if (amen === "theatre" || amen === "concert_hall" || leisure === "stadium" || tourism === "museum" || tourism === "gallery" || amen === "cinema" || shop === "craft_brewery" || amen === "brewery") return "concert";
  if (amen === "restaurant" || amen === "cafe" || amen === "fast_food" || amen === "food_court" || amen === "ice_cream" || shop === "coffee" || shop === "deli") return "restaurant";
  return "other"; // parks, malls, arcades, campus buildings, libraries, sports hangouts…
}

function titleCase(s: string): string {
  // Keep OSM's casing when reasonable; fix ALLCAPS names minimally.
  return s;
}

function coord(el: El): { lat: number; lon: number } | null {
  if (el.lat !== undefined && el.lon !== undefined) return { lat: el.lat, lon: el.lon };
  if (el.center) return { lat: el.center.lat, lon: el.center.lon };
  return null;
}

function gridKey(lat: number, lon: number): string {
  return `${Math.round(lat * 800)}:${Math.round(lon * 800)}`; // ~55 m cells
}

function buildAddress(t: Record<string, string>): string | null {
  const hn = t["addr:housenumber"]; const st = t["addr:street"];
  let base = hn && st ? `${hn} ${st}` : null;
  if (!base) return null;
  const city = t["addr:city"] ?? "Tempe";
  const state = t["addr:state"] ?? "AZ";
  const zip = t["addr:postcode"];
  return `${base}, ${city}, ${state}${zip ? ` ${zip}` : ""}`;
}

const seen = new Set<string>();
const out: unknown[] = [];

for (const f of process.argv.slice(2)) {
  const j = JSON.parse(readFileSync(f, "utf8")) as OsmJson;
  for (const el of j.elements) {
    const t = el.tags ?? {};
    const name = t["name"];
    if (!name) continue;
    if (t["disused:amenity"] || t["was:amenity"]) continue;
    if (t["access"] === "private" || t["access"] === "no") continue;
    const c = coord(el);
    if (!c) continue;
    // Keep only Tempe proper: explicit city tag when present, else the city's
    // bounding box (lat 33.32–33.475, lon -111.98–-111.893 covers Tempe incl.
    // ASU, Mill Ave, Tempe Marketplace, AZ Mills, Kiwanis Park; Guadalupe is
    // excluded by its addr:city tag).
    const city = (t["addr:city"] ?? "").toLowerCase();
    if (city && city !== "tempe" && city !== "tempe, az" && city !== "tempe arizona") continue;
    if (c.lat < 33.32 || c.lat > 33.475 || c.lon < -111.98 || c.lon > -111.893) continue;

    const key = `${canonicalName(name)}|${gridKey(c.lat, c.lon)}`;
    if (seen.has(key)) continue;
    seen.add(key);

    const category = classify(t);
    const address = buildAddress(t);
    const isLarge = LARGE.has(name) || t["capacity"] ? (parseInt(t["capacity"] ?? "0", 10) >= 2000 || LARGE.has(name)) : false;
    out.push({
      name: titleCase(name),
      address,
      lat: Math.round(c.lat * 1e6) / 1e6,
      lon: Math.round(c.lon * 1e6) / 1e6,
      category,
      is_large_venue: !!isLarge,
      osm: `${el.type}/${el.id}`,
    });
  }
}

const header = `/**
 * Tempe, AZ venue seed — ${out.length} REAL places compiled from OpenStreetMap
 * (ODbL license; provenance per venue in server/seed/README.md).
 *
 * Generated by server/seed/gen-from-overpass.ts from raw Overpass API dumps;
 * every entry carries its OSM element ref (node/way/relation + id) so anyone
 * can verify it on openstreetmap.org. Coordinates are to 6 decimal places
 * (~0.1 m) and addresses are OSM addr:* tags when tagged.
 *
 * Spec §4 Spot fields; category enum: bar, club, concert, restaurant, house, other.
 */
export interface SeedVenue {
  name: string;
  address: string | null;
  lat: number;
  lon: number;
  category: "bar" | "club" | "concert" | "restaurant" | "house" | "other";
  /** true for stadiums/arenas/concert halls — spec geofence 400 m */
  is_large_venue: boolean;
  /** OSM element ref "node/123" etc. — provenance, not stored in the DB */
  osm: string;
}

export const LAUNCH_CITY = "Tempe";

export const TEMPE_VENUES: SeedVenue[] = [
`;

const rows = (out as Array<Record<string, unknown>>)
  .sort((a, b) => String(a.name).localeCompare(String(b.name)))
  .map((v) => `  { name: ${JSON.stringify(v.name)}, address: ${JSON.stringify(v.address)}, lat: ${v.lat}, lon: ${v.lon}, category: ${JSON.stringify(v.category)}, is_large_venue: ${v.is_large_venue}, osm: ${JSON.stringify(v.osm)} },`)
  .join("\n");

writeFileSync("/tmp/venues/tempe-venues.generated.txt", header + rows + "\n];\n");
console.log(`wrote /tmp/venues/tempe-venues.generated.txt with ${out.length} venues`);
